// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    var updatePx;
    updatePx = function(element, value) {
      return element.next().text(value + 'px / frame');
    };
    if (chrome.storage) {
      chrome.storage.local.get(null, function(options) {
        var option, slider, value, _results;
        _results = [];
        for (option in options) {
          value = options[option];
          slider = $('#' + option);
          slider.val(value);
          _results.push(updatePx(slider, value));
        }
        return _results;
      });
    }
    return $('.slider').change(function() {
      var id, option, slider, value;
      slider = $(this);
      id = slider.attr('id');
      value = slider.val();
      updatePx(slider, value);
      if (chrome.storage) {
        option = {};
        option[id] = value;
        return chrome.storage.local.set(option);
      } else {
        return window.SmoothKeyScrollSpeeds[id] = value;
      }
    });
  });

}).call(this);
